variable "cluster_id" {}
variable "engine" {}
variable "node_type" {}
variable "num_cache_nodes" {}
variable "parameter_group_name" {}
variable "port" {}
variable "az_mode" {}
variable "security_group_ids" {}
variable "subnet_group_name" {}
variable "snapshot_retention_limit" {}
